// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nckbqzsxusblwzghazrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ja2JxenN4dXNibHd6Z2hhenJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTg5MTEsImV4cCI6MjA3Mjk5NDkxMX0.plnbO8P7iWVcQ9qiRCkCJXmrgcZe47D_IaEhATKK3rY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});